#:schema https://fnox.jdx.dev/schema.json
default_provider = "age"

[providers.age]
type = "age"
recipients = ["age17h55e5e70erljmy50ye6cd43hjssr079fxwzkrart7al9u7qspvsae6vtc"]

[secrets]
PUSHOVER_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV09mbnd5dVI1WjNHSS9BUlhQa1ZQNFZTSjV3WnJPRHFlUURHZVFsWUdBCjlPenNGbXcyUjl5RTJJdWhEZVZkK1M3a1RGdDZuazE3STVlbXVsYTk0WW8KLT4gNCtcWi1ncmVhc2UgIiBECkp5QWhvWVEKLS0tIEdqQmVva2lvYTNyMUJOQUYzMUNZNi80K2tPMVhOcGRzRmhxbzVtMk9VQWMKtDDhBeXSKeRxGkpHzWHZWilUtv1K4bkBfUF+qbX73tU/G36R0J1stuvG8MRC7Q1mFWuXEQtr6lLE21zs3Q0=" }
PUSHOVER_USER= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRmZKTEtDOW9OdnZ1NGg5bXhRdDBwNWtXTXNBU3lXaWNKc1R1dmRoTzJZCnozNmEvQzdJeGlicXg3OEdycmdOTExOdVU2NGpsZWlSZDN2RGh3SEVRblkKLT4gZ24qLWdyZWFzZSAje0xrVEYKCi0tLSBHWlFKSFpuLytGdDBETnQzeVd6eVFLQ1pkOVRwbDl6blJxTFJHZDBMV3ZzCvEtLzMF19NqJD5J30nSTtVHnIrUOzBzc4peK0jAWungOM6RsUN/4wnYaBN7hfKUqx6APm0EFnnsr1QKbt7l" }
