[JonGretar.com]
source        = imaps://j.borgthorsson%40icloud.com@imap.mail.me.com:993
outgoing      = smtp://j.borgthorsson%40icloud.com@smtp.mail.me.com:587
default       = INBOX
folders-sort  = INBOX,Archive,Drafs,Junk,Sent Messages
from          = Jon Gretar Borgthorsson <jongretar@jongretar.com>
copy-to       = Sent Messages
cache-headers = true
source-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_ICLOUD_PASSWORD
outgoing-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_ICLOUD_PASSWORD

[Montel]
from     = Jón Grétar Borgþórsson <jon@montel.fi>
source   = imaps://jon%40montel.fi@imap.gmail.com
outgoing = smtps://jon%40montel.fi@smtp.gmail.com
default       = INBOX
folder-map    = folder_map/gmail.map
folders-sort  = INBOX,G/All Mail,G/Sent Mail,G/Drafts,G/Spam,G/Bin,G/Starred,G/Important
postpone      = [Gmail]/Drafts
cache-headers = true
use-gmail-ext = true
source-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_MONTEL_PASSWORD
outgoing-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_MONTEL_PASSWORD

[GMail]
from     = Jón Grétar Borgþórsson <jon.borgthorsson@gmail.com>
source   = imaps://jon.borgthorsson%40gmail.com@imap.gmail.com
outgoing = smtps://jon.borgthorsson%40gmail.com@smtp.gmail.com
default       = INBOX
folder-map    = folder_map/gmail.map
folders-sort  = INBOX,G/All Mail,G/Sent Mail,G/Drafts,G/Spam,G/Bin,G/Starred,G/Important
postpone      = [Gmail]/Drafts
cache-headers = true
use-gmail-ext = true
source-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_GMAIL_PASSWORD
outgoing-cred-cmd = fnox -c ~/.config/fnox/aerc.toml get AERC_GMAIL_PASSWORD
