
# ---------------- Autocomplete ----------------
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit
# needed to make ..<tab> ../
zstyle ':completion:*' special-dirs true

eval "$(/opt/homebrew/bin/brew shellenv)"
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)


source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-autopair/autopair.zsh

# --- VI mode ---
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh


source ~/.config/zsh/plugins/fzf-setup.zsh
source ~/.config/zsh/plugins/yazi-command.zsh
source ~/.config/zsh/plugins/jupyter-count.zsh

ZSH_TAB_TITLE_ONLY_FOLDER=true
source ~/.config/zsh/plugins/zsh-tab-title.plugin.zsh


# Few things should only happen in term.
if [[ "$TERM_PROGRAM" = "WezTerm" ]]; then

  # Display welcome screen
  fastfetch

  # Display number of running Jupyter instances.
  count_jupyter_instances

fi
