# Load Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

if [ -z "$EDITOR" ]; then
    export EDITOR=nvim
fi
if [ -z "$VISUAL" ]; then
    export VISUAL=nvim
fi

export LESS="-# 1 -R -F"
export PAGER="ov"


# Cargo
. "$HOME/.cargo/env"

# uv
export PATH="/Users/jongretar/.local/bin:$PATH"

export BAT_THEME=Coldark-Dark
