# Load Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

if [ -z "$EDITOR" ]; then
    export EDITOR=nvim
fi
if [ -z "$VISUAL" ]; then
    export VISUAL=nvim
fi

export LESS="-# 1 -R -F"
export PAGER="ov"
export ERL_AFLAGS="-kernel shell_history enabled"

# Secrets
export PUSHOVER_TOKEN=$(security find-generic-password -w -s 'Pushover CLI' -a 'pushover_token' 2> /dev/null)
export PUSHOVER_USER=$(security find-generic-password -w -s 'Pushover CLI' -a 'pushover_user' 2> /dev/null)

# Cargo
. "$HOME/.cargo/env"

# Load Mise
eval "$(mise activate zsh)"

export PATH="/Users/jongretar/.local/bin:$PATH"

export BAT_THEME=Coldark-Dark
