# The peeps piss of my dog
unsetopt BEEP

# append completions to fpath
fpath=(${ASDF_DIR}/completions $HOMEBREW_PREFIX/share/zsh/site-functions ~/.config/zsh/completions $fpath)

# --- ALIASES +++

# ---- Eza (better ls) -----
alias ls="eza --color=always --git --icons=always"

# thefuck alias
eval $(thefuck --alias)
eval $(thefuck --alias fk)

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

# Other Aliases
alias cd="z"
alias vim="nvim"
alias vi="nvim"
alias listening="lsof -n -i4TCP -i4UDP"
alias kill_jupyter="procs --only pid --no-header jupyter | xargs -I '{}' kill {}"
alias activate="source .venv/bin/activate"
alias nano="echo STOP TYPING NANO"
alias ic="wezterm imgcat"
alias imgcat="wezterm imgcat"
alias zed-preview="zed --zed /Applications/Zed\ Preview.app"
alias lg="lazygit"


# -- Bindings --
bindkey "\e[1;3D" backward-word     # ⌥←
bindkey "\e[1;3C" forward-word      # ⌥→

# direnv
eval "$(direnv hook zsh)"

# --- Starship ---
eval "$(starship init zsh)"
