# The peeps piss of my dog
unsetopt BEEP


# append completions to fpath
fpath=(${ASDF_DIR}/completions $HOMEBREW_PREFIX/share/zsh/site-functions ~/.config/zsh/completions $fpath)

# --- AUTOCOMPLETE ---
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit
# needed to make ..<tab> ../
zstyle ':completion:*' special-dirs true

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# ---- FZF -----

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# -- Use fd instead of fzf --

export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# --- setup fzf theme ---
fg="#CBE0F0"
bg="#011628"
bg_highlight="#143652"
purple="#B388FF"
blue="#06BCE4"
cyan="#2CF9ED"

export FZF_DEFAULT_OPTS="--color=fg:${fg},bg:${bg},hl:${purple},fg+:${fg},bg+:${bg_highlight},hl+:${purple},info:${blue},prompt:${cyan},pointer:${cyan},marker:${cyan},spinner:${cyan},header:${cyan}"

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

export BAT_THEME=Coldark-Dark

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
    export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
    ssh)          fzf --preview 'dig {}'                   "$@" ;;
    *)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
  esac
}

# ---- Eza (better ls) -----

alias ls="eza --color=always --git --icons=always"

# thefuck alias
eval $(thefuck --alias)
eval $(thefuck --alias fk)

# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

alias cd="z"

# --- ALIASES +++
alias vim="nvim"
alias vi="nvim"
alias listening="lsof -n -i4TCP -i4UDP"
alias activate="source .venv/bin/activate"
alias nano="echo STOP TYPING NANO"
alias ic="wezterm imgcat"

# -- Environment Variables --
export EDITOR=nvim
export VISUAL=nvim

# -- Bindings --
bindkey "\e[1;3D" backward-word     # ⌥←
bindkey "\e[1;3C" forward-word      # ⌥→

# direnv
eval "$(direnv hook zsh)"


# --- Starship ---
eval "$(starship init zsh)"


