[keys]
leader = ["þ"]

[keys.inline_describe]
  mode = ["enter"]
  accept = ["enter", "ctrl+s"]

[leader.h]
help = "Help"
send = ["?"]

[leader.g]
help = "Git Context"

[leader.gt]
help = "Git Tug"
send = [ ":", "tug", "enter" ]

[leader.n]
context = ["$change_id"]
help = "New change"

[leader.na]
help = "After"
send = [ ":", "new -A $change_id", "enter" ]

[leader.nb]
help = "Before"
send = [ ":", "new -B $change_id", "enter" ]

[custom_commands]
"new from main" = { key = ["N"], args = ["new", "main"] }
"jj push" = { key = ["ð"], mode = ["z"], args = ["push"] }
"jj push closest bookmark(s) (allows new)" = { key = ["Ð"], args = [
    "push", "-r", "closest_bookmark($change_id)", "--allow-new",
] }
"tug" = { key = [
    "T",
], args = [
    "bookmark", "move", "--from", "closest_bookmark($change_id)", "--to", "closest_pushable($change_id)",
] }
"show after revisions" = { key = ["Z"], revset = "::$change_id" }

[custom_commands."move commit down"]
key = ["J"]
args = ["rebase", "-r", "$change_id", "--insert-before", "$change_id-"]

[custom_commands."move commit up"]
key = ["K"]
args = ["rebase", "-r", "$change_id", "--insert-after", "$change_id+"]

[custom_commands."new note commit"]
key = ["ctrl+n"]
args = ["new", "--no-edit", "-A", "$change_id"]
