[keys]
leader = ["þ"]

[leader.h]
help = "Help"
send = ["?"]

[custom_commands]
"new from main" = { key = ["N"], args = ["new", "main"] }
"jj push" = { key = ["h"], args = ["push"] }
"jj push closest bookmark(s) (allows new)" = { key = [
    "H",
], args = [
    "push",
    "-r",
    "closest_bookmark($change_id)",
    "--allow-new",
] }
"tug" = { key = [
    "T",
], args = [
    "bookmark",
    "move",
    "--from",
    "closest_bookmark($change_id)",
    "--to",
    "closest_pushable($change_id)",
] }
"show after revisions" = { key = ["z"], revset = "::$change_id" }

[custom_commands."move commit down"]
key = ["J"]
args = ["rebase", "-r", "$change_id", "--insert-before", "$change_id-"]

[custom_commands."move commit up"]
key = ["K"]
args = ["rebase", "-r", "$change_id", "--insert-after", "$change_id+"]

[custom_commands."new note commit"]
key = ["ctrl+n"]
args = ["new", "--no-edit", "-A", "$change_id"]
